version: "3"
services:
  app:
    build: .
    # Run for debug
    command: tail -f /dev/null
    container_name: "heroku-postgres"
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [“CMD-SHELL”, “pg_isready”]
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  postgres_data:
